### ISSUE TITLE
Not working in newest version

### ISSUE THREAD

**Issue by jpgreth** [Bramas/lychee-create-medium#1]
The plugin is not working with the newest verison of lychee.
## System Information

Lychee Version:  3.1.0
DB Version:      030100
System:          Linux
PHP Version:     5.6
MySQL Version:   50541
Imagick:         1
Imagick Active:  1
Imagick Version: 1673
GD Version:      2.1.1-dev

**Comment by VictorLamoine** [comment]
Works for me; 

```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Error: PHP zip extension not activated


System Information
------------------
Lychee Version:  3.1.5
DB Version:      030102
System:          Linux
PHP Version:     7
MySQL Version:   50717
Imagick:         1
Imagick Active:  1
Imagick Version: 1673
GD Version:      2.1.1
Plugins:         
```

**Comment by lucco669** [comment]
Got the error code:

error:   14953861778383 defdce646e111c756018fa6ab5d12e5b.jpg

What could be wrong?

**Comment by Bramas** [comment]
this error without any other message means the photo is too small ( <1920x1080 ) or ImageMagik is not installed
